---
title: 'Phenotypic evolution: report'
author:
- Amanda Santana Oliveira

date: "August 18th 2022"
output:
  html_document:
    df_print: paged
abstract: |
    Theoretical models and empirical evidence suggest that adaptive speciation can occur without geographic barriers when, within a population: (i) ecological interactions cause natural disruptive selection and (ii) mate choice occurs by assortative mating. Recent models suggest that in the mutualistic systems characterized by trait matching between interacting species, the magnitude of adaptive diversification can be constrained by the stabilizing selection imposed by mutualisms. To investigate how different patterns of mate choice influence adaptive diversification in model mutualisms, we modified the model by Raimundo et al. 2014 to investigate the effects of directional mate choice in one of the species involved in the mutualism on the emerging patterns of adaptive diversification, considering contrasting genetic architectures underlying the traits that mediate ecological and sexual interactions. The effect of sexual selection imposed by a directional mate choice depends on the underlying genetic architecture. Sexual selection drives the evolutionary dynamics of the system if a single trait mediates both ecological and sexual interactions. However, if ecological and sexual interactions are mediated by two distinct, genetically correlated traits, disruptive natural selection promotes adaptive radiation in one of the species and the evolutionary dynamics of the system becomes decoupled.

---

## Introduction

In the course of sympatric speciation, new species can arise from a single ancestral population if frequency-dependent ecological interactions favor extreme phenotypes and generate disruptive natural selection (Maynard-Smith 1966; Kirkpatrick & Ravigné 2002; Dieckmann et al. 2004) and with mating patterns that ensure reproductive isolation, mainly assortative mating (Rosenzweig 1978; Dieckmann & Doebeli 1999; Bolnick & Fitzpatrick 2007). The recognition that these necessary conditions are common in nature raises the question: why the phenomenon of sympatric speciation is rarely documented in the field? One possible explanation is that other ecological interactions may impose conflicting selective pressures on the same trait that restrict or suppress the diversification process.

A fundamental aspect of understanding the evolution of ecological divergence and reproductive isolation is understanding the genetic architecture underlying the quantitative phenotypic traits involved in the adaptive process. Sympatric speciation theory assumes that, in nature, both general conditions for adaptive divergence can be satisfied more easily when the genetic architecture is defined by a magic trait -- a single phenotypic trait mediates both ecological interactions as well as sexual interactions (sensu Servedio et al. 2011). Alternatively, another genetic architecture with the potential to sustain the conditions necessary for adaptive sympatric speciation to occur is the genetic correlations between quantitative phenotypic traits that can respond to distinct selective regimes (Lande 1981; Lande & Arnold 1983).

Among the mating patterns with the potential to influence adaptive diversification, assortative mating has already been studied extensively in models of sympatric speciation (reviewed in Gavrilets 2004). However, interacting species that influence the adaptive process may have distinct mating choices, like directional mating in which females prefer males with exaggerated ornaments, mating with males that carrying the most extreme phenotypes.

Thus, this work sought to identify scenarios in which speciation is plausible as a result of the joint action of natural and sexual selection. For this, we investigated how the incorporation of the directional mating pattern and different degrees of genetic correlation in the course of speciation and adaptive diversification processes, primarily generated by frequency-dependent intraspecific competition in the context of coevolutionary systems defined by mutualistic interspecific interactions, which occur between a pair of species.

## Material and Methods

We modified the adaptive diversification model by Raimundo et al. (2014) with the directional mating choice pattern. The model structure incorporates individual-based simulations and simulates the phenotypic evolution, considering populations of two interacting species (A and B). Thus, the species were characterized by two phenotypes: one that mediates ecological interactions (zA and zB); and another, the females' choice (oB) for species B. In scenarios in which we considered magical traits, the values of the zA and zB phenotypes were determinants of the female's mating choice and mediate ecological interactions. However, we maintained the values of the oB trait in these scenarios for comparison with the genetic correlation scenarios. The initial distribution of the phenotypes in each population was sampled from a normal distribution with a mean of 0 and a standard deviation (𝜎𝐴 and 𝜎𝐵) of 0.5.

Alternatively, in scenarios where we assumed the genetic correlation between the distinct phenotypes that mediate ecological and sexual interactions, trait oB mediates female choice, determining male ornament phenotype, while zA and zB control ecological interactions, we sampled the initial distribution of these phenotypes from a multivariate normal distribution, with different values of correlation.

During the species' life cycle, the individuals experienced intraspecific competition, mutualistic interactions, reproduction, and death, with no overlap of generations. For the intraspecific competition, the model assumes that this is higher among individuals with similar phenotypes, resulting in the frequency-dependent disruptive selection that favors extreme phenotypes. P(comp) determines the effect of the intraspecific competition (see the equations in Raimundo et al. 2014).

The mutualistic interactions occurred by trait matching, in which the individuals of species B actively selected partners of species A and these decisions were based on the phenotypic complementarity between the interacting interspecific individuals, which implies a stabilizing selection that favors the intermediate phenotypes. Each individual of species B interacts with an interspecific individual with the most complementary phenotype. The benefits arising from mutualistic interactions define a fitness component P(mut).

In reproduction, each female of the population chose the male with the highest sexual trait, in a subset of males with 5% of those existing in the population, according to the fitness P(mat), involving the penalty of competition and the benefit of mutualism. This choice assumes that no female has access to all existing males.

To explore the effects of the directional mating pattern on adaptive diversification, 3 scenarios with different genetic correlations (r=1; r=0.5; r=0.1) were simulated. For directional mating choice, the probability of the female choosing a male who will be the offspring's father depends on a criterion based on exaggerated phenotype -- the difference between the phenotypes of males and the maximum value of the phenotype among all males in the subset, with the choice probability decreasing exponentially.

The offspring formed the next generation were generated by all females in the population. We defined the offspring phenotype as the mean of the phenotype values of the female and the male chosen by her for mating, plus or minus a segregation variance, which is a random number sampled from a Gaussian distribution with mean VA = 0 and standard deviation 𝜎𝑉𝐴 = 0.05.


## Results

In the directional mating, under the magic trait genetic architecture, sexual selection proved to be the prevailing regime and led to the adaptive dynamics of the entire system, maintaining the original richness of 2 species (A and B) at the end of the simulation. However, interestingly, although the adaptive irradiation expected for A as a function of strong frequency dependence associated with assortative matings was suppressed by the prevalence of directional selection as a driver of evolutionary dynamics, at least 7 independent speciation events occurred from the species A without the new species derived from it, of low abundance, persisting at the end of the considered simulation time.

In scenarios with the directional mating pattern under genetic correlation architecture, no inhibition of adaptive irradiation was observed in A due to the influence of directional sexual selection in B, as observed in the analogous scenario with a magic trait. Trait oB, which mediates sexual interactions in the genetic correlation scenario, had a lower maximum magnitude (50) than trait zB, which mediates female choices of B in the magic trait scenario (400). In the genetic correlation scenario, the evolutionary dynamics of species A decoupled from the phenotypic evolution patterns of the species, being the only scenario where such decoupling was observed.


```{r sad, fig.cap = "Figure 1. Scenarios of the phenotypic evolution of species A and B with different genotypic architectures – magic trait and genetic correlation – under the directional mating pattern. The oB trait in the magical phenotype scenario had a correlation equal to 0 with the zB trait and there was no direct influence on the biotic interactions present. Color temperature indicates the density of individuals, ranging from high (warm colors) to low (cool colors). 𝑁𝐴=𝑁𝐵=200, 𝜎𝐴= 𝜎𝐵 = 0.5, c = 0.74, 𝜔 = 1, λ = 1.", out.width=500}


```



## Discussion

It is time to synthesize your results and relate your findings with theory.


## References

